### ISSUE TITLE
Documentar los resultados de las nuevas ejecuciones en el cuaderno de investigación

### ISSUE THREAD

**Issue by aliciaolivaresgil** [aog0036/TFG-SmartBeds#58]

**Comment by alvarag** [comment]
Adjunto comentarios sobre la memoria y anexos:
[anexos_AAG.pdf](https://github.com/aog0036/TFG-SmartBeds/files/3116209/anexos_AAG.pdf)
[memoria_AAG.pdf](https://github.com/aog0036/TFG-SmartBeds/files/3116210/memoria_AAG.pdf)
