### ISSUE TITLE
Comenzar documentación de la memoria 

### ISSUE THREAD

**Issue by aliciaolivaresgil** [aog0036/TFG-SmartBeds#78]

**Comment by alvarag** [comment]
Hoy ya toca commit de documentación ;)

**Comment by alvarag** [comment]
Buena escritura y redacción, adjunto algunos comentarios sobre memoria y anexos.

[anexos_AAG.pdf](https://github.com/aog0036/TFG-SmartBeds/files/3284822/anexos_AAG.pdf)
[memoria_AAG.pdf](https://github.com/aog0036/TFG-SmartBeds/files/3284823/memoria_AAG.pdf)
