### ISSUE TITLE
Terminar la primera versión de la memoria 

### ISSUE THREAD

**Issue by aliciaolivaresgil** [aog0036/TFG-SmartBeds#81]

**Comment by alvarag** [comment]
Adjunto versión de la memoria con comentarios. En anexos he visto que sigue desactualizado, así que no he revisado porque no estarán los cambios que te propuse.

[memoriaAAG.pdf](https://github.com/aog0036/TFG-SmartBeds/files/3295957/memoriaAAG.pdf)
